version: '2'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:15
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:24
    depends_on:
      - postgresql
    ports:
      - "8080:8080"

  db:
    container_name: currency-db
    image: postgres:11.9-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency
    ports:
      - "127.0.0.1:2011:5432"
    volumes:
      - db-data:/var/lib/postgres/data
    networks:
      - currency-monitor-network


volumes:
  db-data:
  postgresql_data:
    driver: local

networks:
  currency-monitor-network: