server:
    port: 9080

spring:
  datasource:
     username: postgres
     password: postgres
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:2011/currency
  jpa:
    hibernate:
       ddl-auto: validate
    properties:
       hibernate:
         show_sql: true
         format_sql: true
         dialect: org.hibernate.dialect.PostgreSQLDialect
         temp:
           use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    locations:
        - classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: currency-exc
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/CurrencySpringKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/CurrencySpringKeycloak